version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - faiss_data:/app/faiss_store
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - selenium
      - mongo

  celery_worker_links:
    build:
      context: ./backend
    container_name: celery-worker-links
    working_dir: /app
    command: celery -A app.celery_worker worker --loglevel=info --concurrency=2 -Q links
    volumes:
      - ./backend:/app
      - faiss_data:/app/faiss_store
    env_file:
      - .env
    depends_on:
      - redis
      - selenium
      - mongo

  celery_worker_pages:
    build:
      context: ./backend
    container_name: celery-worker-pages
    working_dir: /app
    command: celery -A app.celery_worker worker --loglevel=info --concurrency=2 -Q pages
    volumes:
      - ./backend:/app
      - faiss_data:/app/faiss_store
    env_file:
      - .env
    depends_on:
      - redis
      - selenium
      - mongo

  celery_worker_embedding:
    build:
      context: ./backend
    container_name: celery-worker-embedding
    working_dir: /app
    command: >
      bash -c "mkdir -p /app/faiss_store && chmod -R 777 /app/faiss_store && celery -A app.celery_worker worker --loglevel=info --concurrency=2 -Q embedding"
    volumes:
      - ./backend:/app
      - faiss_data:/app/faiss_store
    env_file:
      - .env
    depends_on:
      - redis
      - selenium
      - mongo
      - ollama

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  selenium:
    image: seleniarm/standalone-chromium
    container_name: selenium
    ports:
      - "4444:4444"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ollama:
    build:
      context: ./backend
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: always
    volumes:
      - ollama-models:/root/.ollama
    ports:
      - "11434:11434"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 6G

volumes:
  mongo_data:
  faiss_data:
  ollama-models: